possible cause of the following :
Hi Rob,

I am writing the tests for the issue we discussed earlier today and found a new issue (please note that our other client using C# had the same issue earlier).

What I am doing:
One server (UK2)
One client (Java remote client from my desktop).
Client subscribes to updates using a Topic Subscriber.
Client publishes 2 mb strings (all a’s) as values for 50 keys.
Updates have a delay of 20 ms (i.e. 50 updates per second).
It performs 5 updates to each of the 50 keys.

During second iteration of updating keys I get the below error server:

2015-11-17 14:57:30,247|INFO|net.openhft.chronicle.network.AcceptorEventHandler|tree-2/blocking-event-loop|Accepted java.nio.channels.SocketChannel[connected local=/162.11.33.14:5850 remote=/162.11.178.92:56437]
java.lang.IllegalStateException: position: 1048610, limit:1048607, readLimit: 1048607 [pos: 1048606, rlim: 1048607, wlim: 8388608, cap: 8388608 ] \u001E٠⒗٠¹⒊put\u0082⒛٠⒗٠ÃkeyåKey30Åvalue¸\u0080\u0080@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

Value is printed – all a’s.

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa‖a
        at net.openhft.chronicle.network.WireTcpHandler.read(WireTcpHandler.java:133)
        at net.openhft.chronicle.network.WireTcpHandler.lambda$process$14(WireTcpHandler.java:59)
        at net.openhft.chronicle.network.WireTcpHandler$$Lambda$112/1392339565.run(Unknown Source)
        at net.openhft.chronicle.network.connection.VanillaWireOutPublisher.applyAction(VanillaWireOutPublisher.java:32)
        at net.openhft.chronicle.network.WireTcpHandler.process(WireTcpHandler.java:57)
        at net.openhft.chronicle.network.TcpEventHandler.invokeHandler(TcpEventHandler.java:206)
        at net.openhft.chronicle.network.TcpEventHandler.action(TcpEventHandler.java:156)
        at net.openhft.chronicle.threads.VanillaEventLoop.runAllHighHandlers(VanillaEventLoop.java:149)
        at net.openhft.chronicle.threads.VanillaEventLoop.run(VanillaEventLoop.java:118)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.BufferUnderflowException
        at net.openhft.chronicle.bytes.AbstractBytes.readPosition(AbstractBytes.java:129)
        at net.openhft.chronicle.bytes.AbstractBytes.readPosition(AbstractBytes.java:28)
        at net.openhft.chronicle.network.WireTcpHandler.read(WireTcpHandler.java:130)
        ... 13 more
2015-11-17 14:57:58,264|INFO|net.openhft.chronicle.network.AcceptorEventHandler|tree-2/blocking-event-loop|Accepted java.nio.channels.SocketChannel[connected local=/162.11.33.14:5850 remote=/162.11.178.92:56439]

The client is disconnected and prints the below stack trace:

####################################
14:57:57.085 [main] ERROR net.openhft.chronicle.network.connection.TcpChannelHub -
net.openhft.chronicle.bytes.ConnectionDroppedException: java.nio.channels.ClosedChannelException
            at net.openhft.chronicle.network.connection.TcpChannelHub.writeSocket(TcpChannelHub.java:461) ~[chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.network.connection.AbstractStatelessClient.sendEventAsyncWithoutLock(AbstractStatelessClient.java:317) ~[chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.network.connection.AbstractStatelessClient.lambda$null$34(AbstractStatelessClient.java:294) ~[chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.network.connection.TcpChannelHub.lock(TcpChannelHub.java:677) ~[chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.network.connection.TcpChannelHub.lock(TcpChannelHub.java:663) ~[chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.network.connection.AbstractStatelessClient.lambda$sendEventAsync$35(AbstractStatelessClient.java:292) ~[chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.network.connection.AbstractStatelessClient.attempt(AbstractStatelessClient.java:161) [chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.network.connection.AbstractStatelessClient.sendEventAsync(AbstractStatelessClient.java:291) [chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.engine.map.remote.RemoteKeyValueStore.put(RemoteKeyValueStore.java:284) [chronicle-engine-1.9.4.jar:?]
            at net.openhft.chronicle.engine.map.VanillaMapView.put(VanillaMapView.java:195) [chronicle-engine-1.9.4.jar:?]
            at ddp.api.datahub.ChronicleDataStorePublisher.put(ChronicleDataStorePublisher.java:91) [classes/:?]
            at ddp.api.datahub.RemoteDataStorePublisher.put(RemoteDataStorePublisher.java:61) [classes/:?]
            at ddp.tools.benchmarking.StringStringBenchmarker.start(StringStringBenchmarker.java:71) [classes/:?]
            at ddp.tools.benchmarking.StringStringBenchmarker.main(StringStringBenchmarker.java:25) [classes/:?]
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
            at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
            at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:?]
Caused by: java.nio.channels.ClosedChannelException
            at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270) ~[?:1.8.0_65]
            at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:461) ~[?:1.8.0_65]
            at net.openhft.chronicle.network.connection.TcpChannelHub.writeSocket1(TcpChannelHub.java:523) ~[chronicle-network-1.0.38.jar:1.0.38]
            at net.openhft.chronicle.network.connection.TcpChannelHub.writeSocket(TcpChannelHub.java:458) ~[chronicle-network-1.0.38.jar:1.0.38]
            ... 18 more

If I increase the sleep between updates to say 50 ms it has a greater chance of succeeding.

Can you please take a look.

Thanks,
Dan

Daniel Schiermer